spring.application.name=primoprogettospring
spring.config.import=classpath:env.properties

computer.marca=HP
computer.modello=Pavillion
computer.ram=16gb
computer.cpu=Intel core
computer.colore=black

smartphone.marca=Samsung
smartphone.modello=s26
smartphone.ram=12gb
smartphone.cpu=Snapdragon
smartphone.colore=black

spring.datasource.url=jdbc:postgresql://localhost:5432/jpaSpring
spring.datasource.username=postgres
spring.datasource.password=${env.PASSWORD_POSTGRES}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.hibernate.ddl-auto=update